version: "3.4"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: otel-jaeger-tracing
      MYSQL_USER: otel-jaeger-tracing
      MYSQL_PASSWORD: secret
    volumes:
      - ./resources/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
  jaeger:
    image: jaegertracing/all-in-one:1.22.0
    container_name: jaeger
    ports:
      - 14268:14268 # jaeger-collector HTTP server (tracer provider)
      - 16686:16686 # HTTP server (browser UI)
